
# Common Configuration
server:
  port: 8080

spring:
    # Default profile is 'development'
    # use "java -jar app.jar --spring.profiles.active=prod" to switch into production
    profiles:
        active: dev
    application:
        name: tic-tac-toe-back
    datasource:
        hikari:
            maximum-pool-size: 5
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${COGNITO_ISSUER_URI}
                    jwk-set-uri: ${COGNITO_JWK_SET_URI}
                    audiences:
                        - ${COGNITO_APP_CLIENT_ID}
    cognito:
        region: ${AWS_REGION}
        issuer-uri: ${COGNITO_ISSUER_URI}
        jwk-set-uri: ${COGNITO_JWK_SET_URI}

# Development Profile Configuration
---
spring:
    config:
        activate:
            on-profile: dev
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


# Production-like Profile Configuration with postgres
---
spring:
    config:
        activate:
            on-profile: prod-dev
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update

# Production Profile Configuration
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
